"""JSON interchange and standalone C++17 header emission; never evaluates code."""
from __future__ import annotations

import json
from pathlib import Path
import re
from typing import Any, Union

from ._validation import ScoreError
from .model import CompiledPack

PathLike = Union[str, Path]


def _pairs(pairs: list) -> dict:
    result = {}
    for key, value in pairs:
        if key in result:
            raise ScoreError(f'Duplicate JSON key: {key}')
        result[key] = value
    return result


def read_json(path: PathLike) -> Any:
    # Bound reads before allocating/parsing arbitrary user files.
    with Path(path).open('rb') as stream:
        data = stream.read(64 * 1024 * 1024 + 1)
    if len(data) > 64 * 1024 * 1024:
        raise ScoreError('Input exceeds 64 MiB')
    def invalid_constant(value: str) -> None:
        raise ScoreError(f'Non-finite JSON constant: {value}')
    try:
        return json.loads(data, object_pairs_hook=_pairs, parse_constant=invalid_constant)
    except (ValueError, UnicodeError, RecursionError) as exc:
        raise ScoreError(f'Invalid JSON: {exc}') from exc


def load_pack(path: PathLike) -> CompiledPack:
    return CompiledPack.from_dict(read_json(path))


def emit_json(pack: CompiledPack) -> str:
    return json.dumps(pack.to_dict(), indent=2, sort_keys=True, ensure_ascii=True,
                      allow_nan=False) + '\n'


def _cpp_string(value: str) -> str:
    # Fixed-width octal escapes preserve arbitrary UTF-8 without invalid C++
    # surrogate UCNs, source-code injection, or hex-escape run-on.
    parts = []
    for b in value.encode('utf-8'):
        if b == 34:
            parts.append('\\"')
        elif b == 92:
            parts.append('\\\\')
        elif 32 <= b <= 126:
            parts.append(chr(b))
        else:
            parts.append(f'\\{b:03o}')
    return '"' + ''.join(parts) + '"'


def emit_cpp(pack: CompiledPack, namespace: str = 'dancerudiments_generated') -> str:
    keywords = set('''alignas alignof and and_eq asm atomic_cancel atomic_commit atomic_noexcept
    auto bitand bitor bool break case catch char char16_t char32_t class compl concept const
    constexpr const_cast continue co_await co_return co_yield decltype default delete do double
    dynamic_cast else enum explicit export extern false float for friend goto if inline int
    long mutable namespace new noexcept not not_eq nullptr operator or or_eq private protected
    public register reinterpret_cast requires return short signed sizeof static static_assert
    static_cast struct switch template this thread_local throw true try typedef typeid typename
    union unsigned using virtual void volatile wchar_t while xor xor_eq std dancerudiments'''.split())
    if not isinstance(namespace, str) or not re.fullmatch(r'[a-zA-Z][a-zA-Z0-9_]*(::[a-zA-Z][a-zA-Z0-9_]*)*', namespace):
        raise ScoreError('Invalid C++ namespace')
    if any(part in keywords or '__' in part for part in namespace.split('::')):
        raise ScoreError('Reserved C++ namespace')
    lines = ['// Generated by DanceRudiments authoring schema 1. Do not edit sampled data.',
             '// Source attribution/licences remain applicable after compilation.', '#pragma once',
             '#include "dancerudiments/sampled_pattern.hpp"', '', f'namespace {namespace} {{']
    for p in pack.patterns:
        if '__' in p.name:
            raise ScoreError('C++ export does not permit double underscores in pattern names')
        # Prefix symbols, so a valid pattern name such as "class" is still safe.
        lines.extend([f'// Source SHA-256: {p.source_sha256}',
                      f'inline constexpr const char* provenance_{p.name} = {_cpp_string(p.provenance_json)};',
                      f'inline constexpr std::array<dancerudiments::Offset3, {p.period_pips}> table_{p.name}{{{{'])
        for row in p.samples:
            numbers = [format(x, '.17g') for x in row]
            lines.append('  {' + ', '.join(numbers) + '},')
        lines.extend(['}};', f'inline dancerudiments::Offset3 sample_{p.name}(int pip_count) noexcept {{',
                      f'  return dancerudiments::sample_table(table_{p.name}, pip_count);', '}', ''])
    lines.extend(['inline dancerudiments::PatternLibrary make_library() {',
                  '  return dancerudiments::PatternLibrary({'])
    for p in pack.patterns:
        lines.extend([f'    dancerudiments::SampledPattern({_cpp_string(p.name)}, {_cpp_string(p.description)},',
                      f'      std::vector<dancerudiments::Offset3>(table_{p.name}.begin(), table_{p.name}.end())),'])
    lines.extend(['  });', '}', f'}} // namespace {namespace}', ''])
    return '\n'.join(lines)
