// Generated from hash-locked default packs. All movement sampling remains C++.
export const approvedDefaults = [
  {"name": "lfo_breathe", "description": "A four-beat, single-axis sine. The quiet reference for judging busier shapes.", "periodPips": 256, "dimensions": 1},
  {"name": "lfo_surge", "description": "A long rounded sweep and short recovery; an independently authored smooth-reset shape.", "periodPips": 256, "dimensions": 1},
  {"name": "lfo_soft_gate", "description": "Short smooth transitions separated by long stationary dwells. No square-wave teleport.", "periodPips": 256, "dimensions": 1},
  {"name": "lfo_double_pump", "description": "Two unequal pumps and a breathing space within four beats.", "periodPips": 256, "dimensions": 2},
  {"name": "lfo_ratchet", "description": "A four-hit decaying burst, then a rest. Every event is peak-aligned.", "periodPips": 256, "dimensions": 2},
  {"name": "lfo_glide_stair", "description": "Five rounded steps traverse the field, then a smooth return.", "periodPips": 256, "dimensions": 1},
  {"name": "lfo_morph", "description": "An eight-beat blend between a sine and skewed triangle; movement changes within the phrase.", "periodPips": 512, "dimensions": 2},
  {"name": "lfo_flower", "description": "Related rotations form an original three-lobed XY loop over eight beats.", "periodPips": 512, "dimensions": 2},
  {"name": "rhythm_euclid_3_8", "description": "3 evenly distributed onsets on a 8-step grid. Alternating lateral gestures.", "periodPips": 256, "dimensions": 2},
  {"name": "rhythm_euclid_5_12", "description": "5 evenly distributed onsets on a 12-step grid. Alternating lateral gestures.", "periodPips": 256, "dimensions": 2},
  {"name": "rhythm_three_two", "description": "Three horizontal gestures interlock with two vertical gestures in one four-beat cycle.", "periodPips": 256, "dimensions": 2},
  {"name": "rhythm_half_time", "description": "A strong downbeat, snare-like accent on beat three, and smaller offbeat shuffles.", "periodPips": 256, "dimensions": 2},
  {"name": "rudiment_double_paradiddle", "description": "Visual sticking study RLRLRR LRLRLL; equal triplet spacing over four beats. This is a movement interpretation, not a complete drum-performance notation.", "periodPips": 256, "dimensions": 2},
  {"name": "rudiment_paradiddle_diddle", "description": "Visual sticking study RLRRLL LRLLRR; equal triplet spacing over four beats. This is a movement interpretation, not a complete drum-performance notation.", "periodPips": 256, "dimensions": 2},
  {"name": "rudiment_six_stroke", "description": "Visual sticking study RLLRRL LRRLLR; equal triplet spacing over four beats. This is a movement interpretation, not a complete drum-performance notation.", "periodPips": 256, "dimensions": 2},
  {"name": "rudiment_flam_accent", "description": "Opposite-hand grace gestures lead accented groups of three; deliberately expanded for visible motion.", "periodPips": 256, "dimensions": 2},
  {"name": "ease_rebound", "description": "An attributed D3 easing curve, assembled into a closed outward-and-return loop.", "periodPips": 256, "dimensions": 1},
  {"name": "ease_anticipate", "description": "An attributed D3 easing curve, assembled into a closed outward-and-return loop.", "periodPips": 256, "dimensions": 1},
  {"name": "ease_overshoot", "description": "An attributed D3 easing curve, assembled into a closed outward-and-return loop.", "periodPips": 256, "dimensions": 1},
  {"name": "ease_elastic", "description": "Original windowed, decaying oscillation; not a copied D3 curve. Peak scaled to .8.", "periodPips": 256, "dimensions": 1},
  {"name": "akwf_round_saw", "description": "AKWF_R_asym_saw_05_256.h: an actual CC0 waveform slowed to a four-beat position loop.", "periodPips": 256, "dimensions": 1},
  {"name": "akwf_quick_return", "description": "AKWF_R_asym_saw_15_256.h: an actual CC0 waveform slowed to a four-beat position loop.", "periodPips": 256, "dimensions": 1},
  {"name": "akwf_multi_lobe", "description": "AKWF_0001_256.h: an actual CC0 waveform slowed to a four-beat position loop.", "periodPips": 256, "dimensions": 1},
  {"name": "akwf_plateau", "description": "AKWF_0010_256.h: an actual CC0 waveform slowed to a four-beat position loop.", "periodPips": 256, "dimensions": 1},
  {"name": "groove_a_played", "description": "Two-bar funk excerpt A (4\u201312 source beats), performed microtiming.", "periodPips": 512, "dimensions": 2},
  {"name": "groove_a_grid", "description": "Two-bar funk excerpt A (4\u201312 source beats), same hits quantised to sixteenths.", "periodPips": 512, "dimensions": 2},
  {"name": "groove_b_played", "description": "Two-bar funk excerpt B (36\u201344 source beats), performed microtiming.", "periodPips": 512, "dimensions": 2},
  {"name": "groove_b_grid", "description": "Two-bar funk excerpt B (36\u201344 source beats), same hits quantised to sixteenths.", "periodPips": 512, "dimensions": 2},
  {"name": "lfo_twin_swell", "description": "Two broad swells of unequal depth, with a gentle lateral answer. Eight beats.", "periodPips": 512, "dimensions": 2},
  {"name": "lfo_pulse_hold", "description": "A smooth outward pulse, sustained plateau, smaller opposite recoil, and rest.", "periodPips": 256, "dimensions": 1},
  {"name": "lfo_sweep_ratchet", "description": "A slow lateral sweep followed by three decaying vertical ratchets; no reset jump.", "periodPips": 512, "dimensions": 2},
  {"name": "lfo_triplet_wobble", "description": "Three rounded oscillations per two beats, breathing in depth over an eight-beat phrase.", "periodPips": 512, "dimensions": 2},
  {"name": "lfo_breathing_orbit", "description": "A closed ellipse expands and contracts twice during its eight-beat revolution.", "periodPips": 512, "dimensions": 2},
  {"name": "lfo_seeded_drift", "description": "Two independently seeded smooth random lanes; irregular-looking but exactly periodic and seekable.", "periodPips": 1024, "dimensions": 2},
  {"name": "lfo_pendulum_dwell", "description": "Rounded saturation slows the pendulum near either side; a shallow arc connects the turns.", "periodPips": 512, "dimensions": 2},
  {"name": "lfo_reverse_swell", "description": "A long anticipatory rise, quick softened return, and two diminishing aftershocks.", "periodPips": 512, "dimensions": 2},
  {"name": "path_lissajous_2_3", "description": "Two horizontal cycles cross three vertical cycles in a closed eight-beat Lissajous path.", "periodPips": 512, "dimensions": 2},
  {"name": "path_rose_4", "description": "A signed radial oscillation draws four petals, passing through the centre between them.", "periodPips": 512, "dimensions": 2},
  {"name": "path_rose_5", "description": "Five petals in one complete eight-beat traversal; the odd-petal parameter runs through pi, not two pi.", "periodPips": 512, "dimensions": 2},
  {"name": "path_bowed_diamond", "description": "An astroid-shaped loop with inward-curved edges and naturally slow corners.", "periodPips": 512, "dimensions": 2},
  {"name": "path_orbit_dwell", "description": "An ellipse whose phase slows to zero speed at the loop boundary and accelerates through the opposite side.", "periodPips": 512, "dimensions": 2},
  {"name": "path_torus_knot", "description": "Two turns around the axis and three through the tube. XYZ is retained; the demo projects depth.", "periodPips": 1024, "dimensions": 3},
  {"name": "path_woven_3d", "description": "Independent two-, three-, and five-cycle XYZ oscillations close after sixteen beats.", "periodPips": 1024, "dimensions": 3},
  {"name": "path_crank_slider", "description": "Horizontal slider-crank travel with rod length three and crank radius one; vertical motion follows the crank tip.", "periodPips": 256, "dimensions": 2},
  {"name": "rhythm_five_four", "description": "5 lateral hits against four vertical hits per four beats; two bars preserve alternating directions.", "periodPips": 512, "dimensions": 2},
  {"name": "rhythm_seven_four", "description": "7 lateral hits against four vertical hits per four beats; two bars preserve alternating directions.", "periodPips": 512, "dimensions": 2},
  {"name": "rhythm_euclid_7_16", "description": "7 evenly distributed onsets on a sixteen-step grid, repeated with alternating sides over eight beats.", "periodPips": 512, "dimensions": 2},
  {"name": "rhythm_euclid_5_16", "description": "5 evenly distributed onsets on a sixteen-step grid, repeated with alternating sides over eight beats.", "periodPips": 512, "dimensions": 2},
  {"name": "rhythm_swung_answer", "description": "A two-to-one swung call on the right, answered on the left; four beats and eight peak-aligned gestures.", "periodPips": 256, "dimensions": 2},
  {"name": "rhythm_group_332", "description": "Groups of three, three, and two eighth notes. Six alternating accents make an eight-beat loop.", "periodPips": 512, "dimensions": 2},
  {"name": "rhythm_group_223", "description": "Two 7/8 bars grouped as 2+2+3 eighth notes: a seven-quarter-note loop, not forced into four beats.", "periodPips": 448, "dimensions": 2},
  {"name": "rhythm_three_four_five", "description": "Three X, four Y, and five Z gestures share an eight-beat phrase, with exact rational peak times.", "periodPips": 512, "dimensions": 3},
] as const;
export type ApprovedDefaultName = typeof approvedDefaults[number]["name"];
