// Generated from hash-locked default packs. All movement sampling remains C++.
export const approvedDefaults = [
  {"name": "lfo_breathe", "description": "A four-beat, single-axis sine. The quiet reference for judging busier shapes.", "periodPips": 256, "dimensions": 1},
  {"name": "lfo_surge", "description": "A long rounded sweep and short recovery; an independently authored smooth-reset shape.", "periodPips": 256, "dimensions": 1},
  {"name": "lfo_soft_gate", "description": "Short smooth transitions separated by long stationary dwells. No square-wave teleport.", "periodPips": 256, "dimensions": 1},
  {"name": "lfo_double_pump", "description": "Two unequal pumps and a breathing space within four beats.", "periodPips": 256, "dimensions": 2},
  {"name": "lfo_ratchet", "description": "A four-hit decaying burst, then a rest. Every event is peak-aligned.", "periodPips": 256, "dimensions": 2},
  {"name": "lfo_glide_stair", "description": "Five rounded steps traverse the field, then a smooth return.", "periodPips": 256, "dimensions": 1},
  {"name": "lfo_morph", "description": "An eight-beat blend between a sine and skewed triangle; movement changes within the phrase.", "periodPips": 512, "dimensions": 2},
  {"name": "lfo_flower", "description": "Related rotations form an original three-lobed XY loop over eight beats.", "periodPips": 512, "dimensions": 2},
  {"name": "rhythm_euclid_3_8", "description": "3 evenly distributed onsets on a 8-step grid. Alternating lateral gestures.", "periodPips": 256, "dimensions": 2},
  {"name": "rhythm_euclid_5_12", "description": "5 evenly distributed onsets on a 12-step grid. Alternating lateral gestures.", "periodPips": 256, "dimensions": 2},
  {"name": "rhythm_three_two", "description": "Three horizontal gestures interlock with two vertical gestures in one four-beat cycle.", "periodPips": 256, "dimensions": 2},
  {"name": "rhythm_half_time", "description": "A strong downbeat, snare-like accent on beat three, and smaller offbeat shuffles.", "periodPips": 256, "dimensions": 2},
  {"name": "rudiment_double_paradiddle", "description": "Visual sticking study RLRLRR LRLRLL; equal triplet spacing over four beats. This is a movement interpretation, not a complete drum-performance notation.", "periodPips": 256, "dimensions": 2},
  {"name": "rudiment_paradiddle_diddle", "description": "Visual sticking study RLRRLL LRLLRR; equal triplet spacing over four beats. This is a movement interpretation, not a complete drum-performance notation.", "periodPips": 256, "dimensions": 2},
  {"name": "rudiment_six_stroke", "description": "Visual sticking study RLLRRL LRRLLR; equal triplet spacing over four beats. This is a movement interpretation, not a complete drum-performance notation.", "periodPips": 256, "dimensions": 2},
  {"name": "rudiment_flam_accent", "description": "Opposite-hand grace gestures lead accented groups of three; deliberately expanded for visible motion.", "periodPips": 256, "dimensions": 2},
  {"name": "ease_rebound", "description": "An attributed D3 easing curve, assembled into a closed outward-and-return loop.", "periodPips": 256, "dimensions": 1},
  {"name": "ease_anticipate", "description": "An attributed D3 easing curve, assembled into a closed outward-and-return loop.", "periodPips": 256, "dimensions": 1},
  {"name": "ease_overshoot", "description": "An attributed D3 easing curve, assembled into a closed outward-and-return loop.", "periodPips": 256, "dimensions": 1},
  {"name": "ease_elastic", "description": "Original windowed, decaying oscillation; not a copied D3 curve. Peak scaled to .8.", "periodPips": 256, "dimensions": 1},
  {"name": "akwf_round_saw", "description": "AKWF_R_asym_saw_05_256.h: an actual CC0 waveform slowed to a four-beat position loop.", "periodPips": 256, "dimensions": 1},
  {"name": "akwf_quick_return", "description": "AKWF_R_asym_saw_15_256.h: an actual CC0 waveform slowed to a four-beat position loop.", "periodPips": 256, "dimensions": 1},
  {"name": "akwf_multi_lobe", "description": "AKWF_0001_256.h: an actual CC0 waveform slowed to a four-beat position loop.", "periodPips": 256, "dimensions": 1},
  {"name": "akwf_plateau", "description": "AKWF_0010_256.h: an actual CC0 waveform slowed to a four-beat position loop.", "periodPips": 256, "dimensions": 1},
  {"name": "groove_a_played", "description": "Two-bar funk excerpt A (4\u201312 source beats), performed microtiming.", "periodPips": 512, "dimensions": 2},
  {"name": "groove_a_grid", "description": "Two-bar funk excerpt A (4\u201312 source beats), same hits quantised to sixteenths.", "periodPips": 512, "dimensions": 2},
  {"name": "groove_b_played", "description": "Two-bar funk excerpt B (36\u201344 source beats), performed microtiming.", "periodPips": 512, "dimensions": 2},
  {"name": "groove_b_grid", "description": "Two-bar funk excerpt B (36\u201344 source beats), same hits quantised to sixteenths.", "periodPips": 512, "dimensions": 2},
  {"name": "lfo_twin_swell", "description": "Two broad swells of unequal depth, with a gentle lateral answer. Eight beats.", "periodPips": 512, "dimensions": 2},
  {"name": "lfo_pulse_hold", "description": "A smooth outward pulse, sustained plateau, smaller opposite recoil, and rest.", "periodPips": 256, "dimensions": 1},
  {"name": "lfo_sweep_ratchet", "description": "A slow lateral sweep followed by three decaying vertical ratchets; no reset jump.", "periodPips": 512, "dimensions": 2},
  {"name": "lfo_triplet_wobble", "description": "Three rounded oscillations per two beats, breathing in depth over an eight-beat phrase.", "periodPips": 512, "dimensions": 2},
  {"name": "lfo_breathing_orbit", "description": "A closed ellipse expands and contracts twice during its eight-beat revolution.", "periodPips": 512, "dimensions": 2},
  {"name": "lfo_seeded_drift", "description": "Two independently seeded smooth random lanes; irregular-looking but exactly periodic and seekable.", "periodPips": 1024, "dimensions": 2},
  {"name": "lfo_pendulum_dwell", "description": "Rounded saturation slows the pendulum near either side; a shallow arc connects the turns.", "periodPips": 512, "dimensions": 2},
  {"name": "lfo_reverse_swell", "description": "A long anticipatory rise, quick softened return, and two diminishing aftershocks.", "periodPips": 512, "dimensions": 2},
  {"name": "path_lissajous_2_3", "description": "Two horizontal cycles cross three vertical cycles in a closed eight-beat Lissajous path.", "periodPips": 512, "dimensions": 2},
  {"name": "path_rose_4", "description": "A signed radial oscillation draws four petals, passing through the centre between them.", "periodPips": 512, "dimensions": 2},
  {"name": "path_rose_5", "description": "Five petals in one complete eight-beat traversal; the odd-petal parameter runs through pi, not two pi.", "periodPips": 512, "dimensions": 2},
  {"name": "path_bowed_diamond", "description": "An astroid-shaped loop with inward-curved edges and naturally slow corners.", "periodPips": 512, "dimensions": 2},
  {"name": "path_orbit_dwell", "description": "An ellipse whose phase slows to zero speed at the loop boundary and accelerates through the opposite side.", "periodPips": 512, "dimensions": 2},
  {"name": "path_torus_knot", "description": "Two turns around the axis and three through the tube. XYZ is retained; the demo projects depth.", "periodPips": 1024, "dimensions": 3},
  {"name": "path_woven_3d", "description": "Independent two-, three-, and five-cycle XYZ oscillations close after sixteen beats.", "periodPips": 1024, "dimensions": 3},
  {"name": "path_crank_slider", "description": "Horizontal slider-crank travel with rod length three and crank radius one; vertical motion follows the crank tip.", "periodPips": 256, "dimensions": 2},
  {"name": "rhythm_five_four", "description": "5 lateral hits against four vertical hits per four beats; two bars preserve alternating directions.", "periodPips": 512, "dimensions": 2},
  {"name": "rhythm_seven_four", "description": "7 lateral hits against four vertical hits per four beats; two bars preserve alternating directions.", "periodPips": 512, "dimensions": 2},
  {"name": "rhythm_euclid_7_16", "description": "7 evenly distributed onsets on a sixteen-step grid, repeated with alternating sides over eight beats.", "periodPips": 512, "dimensions": 2},
  {"name": "rhythm_euclid_5_16", "description": "5 evenly distributed onsets on a sixteen-step grid, repeated with alternating sides over eight beats.", "periodPips": 512, "dimensions": 2},
  {"name": "rhythm_swung_answer", "description": "A two-to-one swung call on the right, answered on the left; four beats and eight peak-aligned gestures.", "periodPips": 256, "dimensions": 2},
  {"name": "rhythm_group_332", "description": "Groups of three, three, and two eighth notes. Six alternating accents make an eight-beat loop.", "periodPips": 512, "dimensions": 2},
  {"name": "rhythm_group_223", "description": "Two 7/8 bars grouped as 2+2+3 eighth notes: a seven-quarter-note loop, not forced into four beats.", "periodPips": 448, "dimensions": 2},
  {"name": "rhythm_three_four_five", "description": "Three X, four Y, and five Z gestures share an eight-beat phrase, with exact rational peak times.", "periodPips": 512, "dimensions": 3},
  {"name": "wave_pinched", "description": "Pinched sine; a continuous shaped control wave, mapped to horizontal displacement.", "periodPips": 512, "dimensions": 1},
  {"name": "wave_shouldered", "description": "Shouldered sine; a continuous shaped control wave, mapped to horizontal displacement.", "periodPips": 512, "dimensions": 1},
  {"name": "wave_folded", "description": "Folded sine; a continuous shaped control wave, mapped to horizontal displacement.", "periodPips": 512, "dimensions": 1},
  {"name": "wave_double_fold", "description": "Double-fold wave; a continuous shaped control wave, mapped to horizontal displacement.", "periodPips": 512, "dimensions": 1},
  {"name": "wave_rounded_square", "description": "Rounded square; a continuous shaped control wave, mapped to horizontal displacement.", "periodPips": 512, "dimensions": 1},
  {"name": "wave_soft_rectifier", "description": "Soft rectified swell; a continuous shaped control wave, mapped to horizontal displacement.", "periodPips": 512, "dimensions": 1},
  {"name": "wave_skew_warp", "description": "Phase-skew sweep; a continuous shaped control wave, mapped to horizontal displacement.", "periodPips": 512, "dimensions": 1},
  {"name": "wave_scoop_warp", "description": "Scooped return; a continuous shaped control wave, mapped to horizontal displacement.", "periodPips": 512, "dimensions": 1},
  {"name": "wave_shelf_wave", "description": "Shelf and scoop; a continuous shaped control wave, mapped to horizontal displacement.", "periodPips": 512, "dimensions": 1},
  {"name": "wave_notched", "description": "Notched crest; a continuous shaped control wave, mapped to horizontal displacement.", "periodPips": 512, "dimensions": 1},
  {"name": "wave_bottle", "description": "Bottle-neck swell; a continuous shaped control wave, mapped to horizontal displacement.", "periodPips": 512, "dimensions": 1},
  {"name": "wave_reed", "description": "Reed flutter; a continuous shaped control wave, mapped to horizontal displacement.", "periodPips": 512, "dimensions": 1},
  {"name": "wave_unequal_peaks", "description": "Unequal double crest; a continuous shaped control wave, mapped to horizontal displacement.", "periodPips": 512, "dimensions": 1},
  {"name": "wave_ripple_return", "description": "Rippled recovery; a continuous shaped control wave, mapped to horizontal displacement.", "periodPips": 512, "dimensions": 1},
  {"name": "wave_soft_teeth", "description": "Soft triple teeth; a continuous shaped control wave, mapped to horizontal displacement.", "periodPips": 512, "dimensions": 1},
  {"name": "wave_warped_fold", "description": "Warped wave fold; a continuous shaped control wave, mapped to horizontal displacement.", "periodPips": 512, "dimensions": 1},
  {"name": "env_lift_hold_drop", "description": "Lift, hold, settle over an eight-beat phrase; smooth, resting joins.", "periodPips": 512, "dimensions": 2},
  {"name": "env_inhale_exhale", "description": "Long inhale, short exhale over an eight-beat phrase; smooth, resting joins.", "periodPips": 512, "dimensions": 2},
  {"name": "env_triple_swell", "description": "Three unequal swells over an eight-beat phrase; smooth, resting joins.", "periodPips": 512, "dimensions": 2},
  {"name": "env_rising_echo", "description": "Rising echo ladder over an eight-beat phrase; smooth, resting joins.", "periodPips": 512, "dimensions": 2},
  {"name": "env_falling_echo", "description": "Falling echo ladder over an eight-beat phrase; smooth, resting joins.", "periodPips": 512, "dimensions": 2},
  {"name": "env_anticipation", "description": "Backward anticipation over an eight-beat phrase; smooth, resting joins.", "periodPips": 512, "dimensions": 2},
  {"name": "env_plateau_scoop", "description": "Plateau then scoop over an eight-beat phrase; smooth, resting joins.", "periodPips": 512, "dimensions": 2},
  {"name": "env_hesitant", "description": "Hesitant reach over an eight-beat phrase; smooth, resting joins.", "periodPips": 512, "dimensions": 2},
  {"name": "env_double_hold", "description": "Two-height hold over an eight-beat phrase; smooth, resting joins.", "periodPips": 512, "dimensions": 2},
  {"name": "env_swell_recoil", "description": "Deep swell and recoil over an eight-beat phrase; smooth, resting joins.", "periodPips": 512, "dimensions": 2},
  {"name": "env_late_release", "description": "Late release over an eight-beat phrase; smooth, resting joins.", "periodPips": 512, "dimensions": 2},
  {"name": "env_split_attack", "description": "Split attack over an eight-beat phrase; smooth, resting joins.", "periodPips": 512, "dimensions": 2},
  {"name": "env_suspended", "description": "Suspended answer over an eight-beat phrase; smooth, resting joins.", "periodPips": 512, "dimensions": 2},
  {"name": "env_valley_peaks", "description": "Valley between peaks over an eight-beat phrase; smooth, resting joins.", "periodPips": 512, "dimensions": 2},
  {"name": "env_four_breaths", "description": "Four breathing accents over an eight-beat phrase; smooth, resting joins.", "periodPips": 512, "dimensions": 2},
  {"name": "env_return_stair", "description": "Stepped soft recovery over an eight-beat phrase; smooth, resting joins.", "periodPips": 512, "dimensions": 2},
  {"name": "seq_up_down_even", "description": "A programmed position sequence with even segment durations and softened transitions.", "periodPips": 512, "dimensions": 2},
  {"name": "seq_up_down_lilt", "description": "A programmed position sequence with lilt segment durations and softened transitions.", "periodPips": 512, "dimensions": 2},
  {"name": "seq_pendulum_even", "description": "A programmed position sequence with even segment durations and softened transitions.", "periodPips": 512, "dimensions": 2},
  {"name": "seq_pendulum_lilt", "description": "A programmed position sequence with lilt segment durations and softened transitions.", "periodPips": 512, "dimensions": 2},
  {"name": "seq_octave_even", "description": "A programmed position sequence with even segment durations and softened transitions.", "periodPips": 512, "dimensions": 2},
  {"name": "seq_octave_lilt", "description": "A programmed position sequence with lilt segment durations and softened transitions.", "periodPips": 512, "dimensions": 2},
  {"name": "seq_unequal_even", "description": "A programmed position sequence with even segment durations and softened transitions.", "periodPips": 512, "dimensions": 2},
  {"name": "seq_unequal_lilt", "description": "A programmed position sequence with lilt segment durations and softened transitions.", "periodPips": 512, "dimensions": 2},
  {"name": "seq_question_even", "description": "A programmed position sequence with even segment durations and softened transitions.", "periodPips": 512, "dimensions": 2},
  {"name": "seq_question_lilt", "description": "A programmed position sequence with lilt segment durations and softened transitions.", "periodPips": 512, "dimensions": 2},
  {"name": "seq_answer_even", "description": "A programmed position sequence with even segment durations and softened transitions.", "periodPips": 512, "dimensions": 2},
  {"name": "seq_answer_lilt", "description": "A programmed position sequence with lilt segment durations and softened transitions.", "periodPips": 512, "dimensions": 2},
  {"name": "seq_ratchet_even", "description": "A programmed position sequence with even segment durations and softened transitions.", "periodPips": 512, "dimensions": 2},
  {"name": "seq_ratchet_lilt", "description": "A programmed position sequence with lilt segment durations and softened transitions.", "periodPips": 512, "dimensions": 2},
  {"name": "seq_stairs_even", "description": "A programmed position sequence with even segment durations and softened transitions.", "periodPips": 512, "dimensions": 2},
  {"name": "seq_stairs_lilt", "description": "A programmed position sequence with lilt segment durations and softened transitions.", "periodPips": 512, "dimensions": 2},
  {"name": "noise_drift_5", "description": "Indexed SHA-256 control points in a closed drift path. No mutable random state.", "periodPips": 1024, "dimensions": 2},
  {"name": "noise_drift_7", "description": "Indexed SHA-256 control points in a closed drift path. No mutable random state.", "periodPips": 1024, "dimensions": 2},
  {"name": "noise_drift_9", "description": "Indexed SHA-256 control points in a closed drift path. No mutable random state.", "periodPips": 1024, "dimensions": 2},
  {"name": "noise_drift_11", "description": "Indexed SHA-256 control points in a closed drift path. No mutable random state.", "periodPips": 1024, "dimensions": 2},
  {"name": "noise_orbit_6", "description": "Indexed SHA-256 control points in a closed orbit path. No mutable random state.", "periodPips": 1024, "dimensions": 2},
  {"name": "noise_orbit_8", "description": "Indexed SHA-256 control points in a closed orbit path. No mutable random state.", "periodPips": 1024, "dimensions": 2},
  {"name": "noise_orbit_10", "description": "Indexed SHA-256 control points in a closed orbit path. No mutable random state.", "periodPips": 1024, "dimensions": 2},
  {"name": "noise_orbit_12", "description": "Indexed SHA-256 control points in a closed orbit path. No mutable random state.", "periodPips": 1024, "dimensions": 2},
  {"name": "noise_ripple_5", "description": "Indexed SHA-256 control points in a closed ripple path. No mutable random state.", "periodPips": 1024, "dimensions": 2},
  {"name": "noise_ripple_7", "description": "Indexed SHA-256 control points in a closed ripple path. No mutable random state.", "periodPips": 1024, "dimensions": 2},
  {"name": "noise_ripple_9", "description": "Indexed SHA-256 control points in a closed ripple path. No mutable random state.", "periodPips": 1024, "dimensions": 2},
  {"name": "noise_ripple_11", "description": "Indexed SHA-256 control points in a closed ripple path. No mutable random state.", "periodPips": 1024, "dimensions": 2},
  {"name": "noise_depth_6", "description": "Indexed SHA-256 control points in a closed depth path. No mutable random state.", "periodPips": 1024, "dimensions": 3},
  {"name": "noise_depth_8", "description": "Indexed SHA-256 control points in a closed depth path. No mutable random state.", "periodPips": 1024, "dimensions": 3},
  {"name": "noise_depth_10", "description": "Indexed SHA-256 control points in a closed depth path. No mutable random state.", "periodPips": 1024, "dimensions": 3},
  {"name": "noise_depth_12", "description": "Indexed SHA-256 control points in a closed depth path. No mutable random state.", "periodPips": 1024, "dimensions": 3},
  {"name": "orbit_harmonic_01", "description": "An ellipse combined with unequal horizontal and vertical harmonic ripples.", "periodPips": 512, "dimensions": 2},
  {"name": "orbit_harmonic_02", "description": "An ellipse combined with unequal horizontal and vertical harmonic ripples.", "periodPips": 512, "dimensions": 2},
  {"name": "orbit_harmonic_03", "description": "An ellipse combined with unequal horizontal and vertical harmonic ripples.", "periodPips": 512, "dimensions": 2},
  {"name": "orbit_harmonic_04", "description": "An ellipse combined with unequal horizontal and vertical harmonic ripples.", "periodPips": 512, "dimensions": 2},
  {"name": "orbit_harmonic_05", "description": "An ellipse combined with unequal horizontal and vertical harmonic ripples.", "periodPips": 512, "dimensions": 2},
  {"name": "orbit_harmonic_06", "description": "An ellipse combined with unequal horizontal and vertical harmonic ripples.", "periodPips": 512, "dimensions": 2},
  {"name": "orbit_harmonic_07", "description": "An ellipse combined with unequal horizontal and vertical harmonic ripples.", "periodPips": 512, "dimensions": 2},
  {"name": "orbit_harmonic_08", "description": "An ellipse combined with unequal horizontal and vertical harmonic ripples.", "periodPips": 512, "dimensions": 2},
  {"name": "orbit_harmonic_09", "description": "An ellipse combined with unequal horizontal and vertical harmonic ripples.", "periodPips": 512, "dimensions": 2},
  {"name": "orbit_harmonic_10", "description": "An ellipse combined with unequal horizontal and vertical harmonic ripples.", "periodPips": 512, "dimensions": 2},
  {"name": "orbit_harmonic_11", "description": "An ellipse combined with unequal horizontal and vertical harmonic ripples.", "periodPips": 512, "dimensions": 2},
  {"name": "orbit_harmonic_12", "description": "An ellipse combined with unequal horizontal and vertical harmonic ripples.", "periodPips": 512, "dimensions": 2},
  {"name": "orbit_harmonic_13", "description": "An ellipse combined with unequal horizontal and vertical harmonic ripples.", "periodPips": 512, "dimensions": 2},
  {"name": "orbit_harmonic_14", "description": "An ellipse combined with unequal horizontal and vertical harmonic ripples.", "periodPips": 512, "dimensions": 2},
  {"name": "orbit_harmonic_15", "description": "An ellipse combined with unequal horizontal and vertical harmonic ripples.", "periodPips": 512, "dimensions": 2},
  {"name": "orbit_harmonic_16", "description": "An ellipse combined with unequal horizontal and vertical harmonic ripples.", "periodPips": 512, "dimensions": 2},
  {"name": "weave_1_3", "description": "1 horizontal and 3 vertical cycles; a phase-offset, closed 16-beat traversal.", "periodPips": 1024, "dimensions": 2},
  {"name": "weave_1_4", "description": "1 horizontal and 4 vertical cycles; a phase-offset, closed 16-beat traversal.", "periodPips": 1024, "dimensions": 2},
  {"name": "weave_1_5", "description": "1 horizontal and 5 vertical cycles; a phase-offset, closed 16-beat traversal.", "periodPips": 1024, "dimensions": 2},
  {"name": "weave_2_5", "description": "2 horizontal and 5 vertical cycles; a phase-offset, closed 16-beat traversal.", "periodPips": 1024, "dimensions": 2},
  {"name": "weave_2_7", "description": "2 horizontal and 7 vertical cycles; a phase-offset, closed 16-beat traversal.", "periodPips": 1024, "dimensions": 2},
  {"name": "weave_3_4", "description": "3 horizontal and 4 vertical cycles; a phase-offset, closed 16-beat traversal.", "periodPips": 1024, "dimensions": 2},
  {"name": "weave_3_5", "description": "3 horizontal and 5 vertical cycles; a phase-offset, closed 16-beat traversal.", "periodPips": 1024, "dimensions": 2},
  {"name": "weave_3_7", "description": "3 horizontal and 7 vertical cycles; a phase-offset, closed 16-beat traversal.", "periodPips": 1024, "dimensions": 2},
  {"name": "weave_3_8", "description": "3 horizontal and 8 vertical cycles; a phase-offset, closed 16-beat traversal.", "periodPips": 1024, "dimensions": 2},
  {"name": "weave_4_5", "description": "4 horizontal and 5 vertical cycles; a phase-offset, closed 16-beat traversal.", "periodPips": 1024, "dimensions": 2},
  {"name": "weave_4_7", "description": "4 horizontal and 7 vertical cycles; a phase-offset, closed 16-beat traversal.", "periodPips": 1024, "dimensions": 2},
  {"name": "weave_4_9", "description": "4 horizontal and 9 vertical cycles; a phase-offset, closed 16-beat traversal.", "periodPips": 1024, "dimensions": 2},
  {"name": "weave_5_6", "description": "5 horizontal and 6 vertical cycles; a phase-offset, closed 16-beat traversal.", "periodPips": 1024, "dimensions": 2},
  {"name": "weave_5_7", "description": "5 horizontal and 7 vertical cycles; a phase-offset, closed 16-beat traversal.", "periodPips": 1024, "dimensions": 2},
  {"name": "weave_5_8", "description": "5 horizontal and 8 vertical cycles; a phase-offset, closed 16-beat traversal.", "periodPips": 1024, "dimensions": 2},
  {"name": "weave_5_9", "description": "5 horizontal and 9 vertical cycles; a phase-offset, closed 16-beat traversal.", "periodPips": 1024, "dimensions": 2},
  {"name": "polar_rose_3", "description": "A complete signed-radius rose traversal; odd-petal roses use a half-turn parameter.", "periodPips": 1024, "dimensions": 2},
  {"name": "polar_rose_6", "description": "A complete signed-radius rose traversal; odd-petal roses use a half-turn parameter.", "periodPips": 1024, "dimensions": 2},
  {"name": "polar_rose_7", "description": "A complete signed-radius rose traversal; odd-petal roses use a half-turn parameter.", "periodPips": 1024, "dimensions": 2},
  {"name": "polar_rose_8", "description": "A complete signed-radius rose traversal; odd-petal roses use a half-turn parameter.", "periodPips": 1024, "dimensions": 2},
  {"name": "polar_rose_9", "description": "A complete signed-radius rose traversal; odd-petal roses use a half-turn parameter.", "periodPips": 1024, "dimensions": 2},
  {"name": "polar_rose_10", "description": "A complete signed-radius rose traversal; odd-petal roses use a half-turn parameter.", "periodPips": 1024, "dimensions": 2},
  {"name": "polar_rose_11", "description": "A complete signed-radius rose traversal; odd-petal roses use a half-turn parameter.", "periodPips": 1024, "dimensions": 2},
  {"name": "polar_rose_12", "description": "A complete signed-radius rose traversal; odd-petal roses use a half-turn parameter.", "periodPips": 1024, "dimensions": 2},
  {"name": "polar_scallop_2", "description": "A positive-radius scalloped loop; no centre crossings, with an asymmetrically bent lobe.", "periodPips": 1024, "dimensions": 2},
  {"name": "polar_scallop_3", "description": "A positive-radius scalloped loop; no centre crossings, with an asymmetrically bent lobe.", "periodPips": 1024, "dimensions": 2},
  {"name": "polar_scallop_4", "description": "A positive-radius scalloped loop; no centre crossings, with an asymmetrically bent lobe.", "periodPips": 1024, "dimensions": 2},
  {"name": "polar_scallop_5", "description": "A positive-radius scalloped loop; no centre crossings, with an asymmetrically bent lobe.", "periodPips": 1024, "dimensions": 2},
  {"name": "polar_scallop_6", "description": "A positive-radius scalloped loop; no centre crossings, with an asymmetrically bent lobe.", "periodPips": 1024, "dimensions": 2},
  {"name": "polar_scallop_7", "description": "A positive-radius scalloped loop; no centre crossings, with an asymmetrically bent lobe.", "periodPips": 1024, "dimensions": 2},
  {"name": "polar_scallop_8", "description": "A positive-radius scalloped loop; no centre crossings, with an asymmetrically bent lobe.", "periodPips": 1024, "dimensions": 2},
  {"name": "polar_scallop_9", "description": "A positive-radius scalloped loop; no centre crossings, with an asymmetrically bent lobe.", "periodPips": 1024, "dimensions": 2},
  {"name": "spiro_inside_3_1", "description": "A closed inside-rolling circle trace, with pen radius smaller than the rolling radius.", "periodPips": 1024, "dimensions": 2},
  {"name": "spiro_inside_4_1", "description": "A closed inside-rolling circle trace, with pen radius smaller than the rolling radius.", "periodPips": 1024, "dimensions": 2},
  {"name": "spiro_inside_5_2", "description": "A closed inside-rolling circle trace, with pen radius smaller than the rolling radius.", "periodPips": 1024, "dimensions": 2},
  {"name": "spiro_inside_5_1", "description": "A closed inside-rolling circle trace, with pen radius smaller than the rolling radius.", "periodPips": 1024, "dimensions": 2},
  {"name": "spiro_inside_7_2", "description": "A closed inside-rolling circle trace, with pen radius smaller than the rolling radius.", "periodPips": 1024, "dimensions": 2},
  {"name": "spiro_inside_7_3", "description": "A closed inside-rolling circle trace, with pen radius smaller than the rolling radius.", "periodPips": 1024, "dimensions": 2},
  {"name": "spiro_inside_8_3", "description": "A closed inside-rolling circle trace, with pen radius smaller than the rolling radius.", "periodPips": 1024, "dimensions": 2},
  {"name": "spiro_inside_9_4", "description": "A closed inside-rolling circle trace, with pen radius smaller than the rolling radius.", "periodPips": 1024, "dimensions": 2},
  {"name": "spiro_outside_3_1", "description": "A closed outside-rolling circle trace, with pen radius smaller than the rolling radius.", "periodPips": 1024, "dimensions": 2},
  {"name": "spiro_outside_4_1", "description": "A closed outside-rolling circle trace, with pen radius smaller than the rolling radius.", "periodPips": 1024, "dimensions": 2},
  {"name": "spiro_outside_5_2", "description": "A closed outside-rolling circle trace, with pen radius smaller than the rolling radius.", "periodPips": 1024, "dimensions": 2},
  {"name": "spiro_outside_5_1", "description": "A closed outside-rolling circle trace, with pen radius smaller than the rolling radius.", "periodPips": 1024, "dimensions": 2},
  {"name": "spiro_outside_7_2", "description": "A closed outside-rolling circle trace, with pen radius smaller than the rolling radius.", "periodPips": 1024, "dimensions": 2},
  {"name": "spiro_outside_7_3", "description": "A closed outside-rolling circle trace, with pen radius smaller than the rolling radius.", "periodPips": 1024, "dimensions": 2},
  {"name": "spiro_outside_8_3", "description": "A closed outside-rolling circle trace, with pen radius smaller than the rolling radius.", "periodPips": 1024, "dimensions": 2},
  {"name": "spiro_outside_9_4", "description": "A closed outside-rolling circle trace, with pen radius smaller than the rolling radius.", "periodPips": 1024, "dimensions": 2},
  {"name": "space_torus_2_5", "description": "A genuine XYZ closed torus-knot trajectory. The demo uses an oblique projection.", "periodPips": 1024, "dimensions": 3},
  {"name": "space_torus_2_7", "description": "A genuine XYZ closed torus-knot trajectory. The demo uses an oblique projection.", "periodPips": 1024, "dimensions": 3},
  {"name": "space_torus_3_4", "description": "A genuine XYZ closed torus-knot trajectory. The demo uses an oblique projection.", "periodPips": 1024, "dimensions": 3},
  {"name": "space_torus_3_5", "description": "A genuine XYZ closed torus-knot trajectory. The demo uses an oblique projection.", "periodPips": 1024, "dimensions": 3},
  {"name": "space_torus_3_7", "description": "A genuine XYZ closed torus-knot trajectory. The demo uses an oblique projection.", "periodPips": 1024, "dimensions": 3},
  {"name": "space_torus_4_5", "description": "A genuine XYZ closed torus-knot trajectory. The demo uses an oblique projection.", "periodPips": 1024, "dimensions": 3},
  {"name": "space_torus_4_7", "description": "A genuine XYZ closed torus-knot trajectory. The demo uses an oblique projection.", "periodPips": 1024, "dimensions": 3},
  {"name": "space_torus_5_6", "description": "A genuine XYZ closed torus-knot trajectory. The demo uses an oblique projection.", "periodPips": 1024, "dimensions": 3},
  {"name": "space_weave_1_2_3", "description": "Three coprime-frequency coordinate lanes with distinct phase offsets.", "periodPips": 1024, "dimensions": 3},
  {"name": "space_weave_1_3_4", "description": "Three coprime-frequency coordinate lanes with distinct phase offsets.", "periodPips": 1024, "dimensions": 3},
  {"name": "space_weave_2_3_4", "description": "Three coprime-frequency coordinate lanes with distinct phase offsets.", "periodPips": 1024, "dimensions": 3},
  {"name": "space_weave_2_3_7", "description": "Three coprime-frequency coordinate lanes with distinct phase offsets.", "periodPips": 1024, "dimensions": 3},
  {"name": "space_weave_2_5_7", "description": "Three coprime-frequency coordinate lanes with distinct phase offsets.", "periodPips": 1024, "dimensions": 3},
  {"name": "space_weave_3_4_5", "description": "Three coprime-frequency coordinate lanes with distinct phase offsets.", "periodPips": 1024, "dimensions": 3},
  {"name": "space_weave_3_5_7", "description": "Three coprime-frequency coordinate lanes with distinct phase offsets.", "periodPips": 1024, "dimensions": 3},
  {"name": "space_weave_4_5_7", "description": "Three coprime-frequency coordinate lanes with distinct phase offsets.", "periodPips": 1024, "dimensions": 3},
  {"name": "mech_piston_short", "description": "Short-rod piston; an original kinematic-style position study, not an engineering simulation.", "periodPips": 512, "dimensions": 2},
  {"name": "mech_piston_long", "description": "Long-rod piston; an original kinematic-style position study, not an engineering simulation.", "periodPips": 512, "dimensions": 2},
  {"name": "mech_offset_crank", "description": "Offset crank; an original kinematic-style position study, not an engineering simulation.", "periodPips": 512, "dimensions": 2},
  {"name": "mech_scotch_yoke", "description": "Yoke with rocking linkage; an original kinematic-style position study, not an engineering simulation.", "periodPips": 512, "dimensions": 2},
  {"name": "mech_whitworth", "description": "Quick-return linkage study; an original kinematic-style position study, not an engineering simulation.", "periodPips": 512, "dimensions": 2},
  {"name": "mech_elliptic_cam", "description": "Elliptic cam follower; an original kinematic-style position study, not an engineering simulation.", "periodPips": 512, "dimensions": 2},
  {"name": "mech_two_lobe_cam", "description": "Two-lobe cam follower; an original kinematic-style position study, not an engineering simulation.", "periodPips": 512, "dimensions": 2},
  {"name": "mech_three_lobe_cam", "description": "Three-lobe cam follower; an original kinematic-style position study, not an engineering simulation.", "periodPips": 512, "dimensions": 2},
  {"name": "mech_escapement", "description": "Soft escapement study; an original kinematic-style position study, not an engineering simulation.", "periodPips": 512, "dimensions": 2},
  {"name": "mech_paddle", "description": "Paddle-wheel tip; an original kinematic-style position study, not an engineering simulation.", "periodPips": 512, "dimensions": 2},
  {"name": "mech_wobble_plate", "description": "Wobble-plate trace; an original kinematic-style position study, not an engineering simulation.", "periodPips": 512, "dimensions": 3},
  {"name": "mech_rocking_beam", "description": "Rocking beam; an original kinematic-style position study, not an engineering simulation.", "periodPips": 512, "dimensions": 2},
  {"name": "mech_coupled_cranks", "description": "Coupled cranks; an original kinematic-style position study, not an engineering simulation.", "periodPips": 512, "dimensions": 2},
  {"name": "mech_crank_rocker", "description": "Crank and rocker study; an original kinematic-style position study, not an engineering simulation.", "periodPips": 512, "dimensions": 3},
  {"name": "mech_piston_balance", "description": "Piston and balance mass; an original kinematic-style position study, not an engineering simulation.", "periodPips": 512, "dimensions": 3},
  {"name": "mech_cam_return", "description": "Cam rise and return; an original kinematic-style position study, not an engineering simulation.", "periodPips": 512, "dimensions": 2},
  {"name": "euclid_2_5", "description": "Evenly distributed accents with alternating sides; first onset is the phrase accent.", "periodPips": 160, "dimensions": 2},
  {"name": "euclid_3_7", "description": "Evenly distributed accents with alternating sides; first onset is the phrase accent.", "periodPips": 224, "dimensions": 2},
  {"name": "euclid_3_10", "description": "Evenly distributed accents with alternating sides; first onset is the phrase accent.", "periodPips": 320, "dimensions": 2},
  {"name": "euclid_4_9", "description": "Evenly distributed accents with alternating sides; first onset is the phrase accent.", "periodPips": 288, "dimensions": 2},
  {"name": "euclid_4_11", "description": "Evenly distributed accents with alternating sides; first onset is the phrase accent.", "periodPips": 352, "dimensions": 2},
  {"name": "euclid_5_9", "description": "Evenly distributed accents with alternating sides; first onset is the phrase accent.", "periodPips": 288, "dimensions": 2},
  {"name": "euclid_5_11", "description": "Evenly distributed accents with alternating sides; first onset is the phrase accent.", "periodPips": 352, "dimensions": 2},
  {"name": "euclid_5_13", "description": "Evenly distributed accents with alternating sides; first onset is the phrase accent.", "periodPips": 416, "dimensions": 2},
  {"name": "euclid_5_14", "description": "Evenly distributed accents with alternating sides; first onset is the phrase accent.", "periodPips": 448, "dimensions": 2},
  {"name": "euclid_6_13", "description": "Evenly distributed accents with alternating sides; first onset is the phrase accent.", "periodPips": 416, "dimensions": 2},
  {"name": "euclid_7_12", "description": "Evenly distributed accents with alternating sides; first onset is the phrase accent.", "periodPips": 384, "dimensions": 2},
  {"name": "euclid_7_15", "description": "Evenly distributed accents with alternating sides; first onset is the phrase accent.", "periodPips": 480, "dimensions": 2},
  {"name": "euclid_7_17", "description": "Evenly distributed accents with alternating sides; first onset is the phrase accent.", "periodPips": 544, "dimensions": 2},
  {"name": "euclid_8_19", "description": "Evenly distributed accents with alternating sides; first onset is the phrase accent.", "periodPips": 608, "dimensions": 2},
  {"name": "euclid_9_20", "description": "Evenly distributed accents with alternating sides; first onset is the phrase accent.", "periodPips": 640, "dimensions": 2},
  {"name": "euclid_11_24", "description": "Evenly distributed accents with alternating sides; first onset is the phrase accent.", "periodPips": 768, "dimensions": 2},
  {"name": "poly_2_5", "description": "Two independent pulse trains share an eight-beat boundary. Each right-lane gesture includes depth.", "periodPips": 512, "dimensions": 3},
  {"name": "poly_2_7", "description": "Two independent pulse trains share an eight-beat boundary. Each right-lane gesture includes depth.", "periodPips": 512, "dimensions": 3},
  {"name": "poly_2_9", "description": "Two independent pulse trains share an eight-beat boundary. Each right-lane gesture includes depth.", "periodPips": 512, "dimensions": 3},
  {"name": "poly_3_5", "description": "Two independent pulse trains share an eight-beat boundary. Each right-lane gesture includes depth.", "periodPips": 512, "dimensions": 3},
  {"name": "poly_3_7", "description": "Two independent pulse trains share an eight-beat boundary. Each right-lane gesture includes depth.", "periodPips": 512, "dimensions": 3},
  {"name": "poly_3_8", "description": "Two independent pulse trains share an eight-beat boundary. Each right-lane gesture includes depth.", "periodPips": 512, "dimensions": 3},
  {"name": "poly_3_10", "description": "Two independent pulse trains share an eight-beat boundary. Each right-lane gesture includes depth.", "periodPips": 512, "dimensions": 3},
  {"name": "poly_4_5", "description": "Two independent pulse trains share an eight-beat boundary. Each right-lane gesture includes depth.", "periodPips": 512, "dimensions": 3},
  {"name": "poly_4_7", "description": "Two independent pulse trains share an eight-beat boundary. Each right-lane gesture includes depth.", "periodPips": 512, "dimensions": 3},
  {"name": "poly_4_9", "description": "Two independent pulse trains share an eight-beat boundary. Each right-lane gesture includes depth.", "periodPips": 512, "dimensions": 3},
  {"name": "poly_5_6", "description": "Two independent pulse trains share an eight-beat boundary. Each right-lane gesture includes depth.", "periodPips": 512, "dimensions": 3},
  {"name": "poly_5_7", "description": "Two independent pulse trains share an eight-beat boundary. Each right-lane gesture includes depth.", "periodPips": 512, "dimensions": 3},
  {"name": "poly_5_8", "description": "Two independent pulse trains share an eight-beat boundary. Each right-lane gesture includes depth.", "periodPips": 512, "dimensions": 3},
  {"name": "poly_5_9", "description": "Two independent pulse trains share an eight-beat boundary. Each right-lane gesture includes depth.", "periodPips": 512, "dimensions": 3},
  {"name": "poly_6_7", "description": "Two independent pulse trains share an eight-beat boundary. Each right-lane gesture includes depth.", "periodPips": 512, "dimensions": 3},
  {"name": "poly_7_8", "description": "Two independent pulse trains share an eight-beat boundary. Each right-lane gesture includes depth.", "periodPips": 512, "dimensions": 3},
  {"name": "meter_2_3", "description": "Group starts lean alternately left and right; quieter subdivisions mark the eighth-note grid.", "periodPips": 160, "dimensions": 3},
  {"name": "meter_3_2", "description": "Group starts lean alternately left and right; quieter subdivisions mark the eighth-note grid.", "periodPips": 160, "dimensions": 3},
  {"name": "meter_3_2_2", "description": "Group starts lean alternately left and right; quieter subdivisions mark the eighth-note grid.", "periodPips": 224, "dimensions": 3},
  {"name": "meter_2_3_2", "description": "Group starts lean alternately left and right; quieter subdivisions mark the eighth-note grid.", "periodPips": 224, "dimensions": 3},
  {"name": "meter_3_4", "description": "Group starts lean alternately left and right; quieter subdivisions mark the eighth-note grid.", "periodPips": 224, "dimensions": 3},
  {"name": "meter_4_3", "description": "Group starts lean alternately left and right; quieter subdivisions mark the eighth-note grid.", "periodPips": 224, "dimensions": 3},
  {"name": "meter_2_2_2_3", "description": "Group starts lean alternately left and right; quieter subdivisions mark the eighth-note grid.", "periodPips": 288, "dimensions": 3},
  {"name": "meter_2_3_2_2", "description": "Group starts lean alternately left and right; quieter subdivisions mark the eighth-note grid.", "periodPips": 288, "dimensions": 3},
  {"name": "meter_3_2_3_2", "description": "Group starts lean alternately left and right; quieter subdivisions mark the eighth-note grid.", "periodPips": 320, "dimensions": 3},
  {"name": "meter_3_3_2_3", "description": "Group starts lean alternately left and right; quieter subdivisions mark the eighth-note grid.", "periodPips": 352, "dimensions": 3},
  {"name": "meter_2_2_3_2_3", "description": "Group starts lean alternately left and right; quieter subdivisions mark the eighth-note grid.", "periodPips": 384, "dimensions": 3},
  {"name": "meter_3_3_3_2", "description": "Group starts lean alternately left and right; quieter subdivisions mark the eighth-note grid.", "periodPips": 352, "dimensions": 3},
  {"name": "meter_4_3_3", "description": "Group starts lean alternately left and right; quieter subdivisions mark the eighth-note grid.", "periodPips": 320, "dimensions": 3},
  {"name": "meter_3_4_4", "description": "Group starts lean alternately left and right; quieter subdivisions mark the eighth-note grid.", "periodPips": 352, "dimensions": 3},
  {"name": "meter_2_3_3_2_3", "description": "Group starts lean alternately left and right; quieter subdivisions mark the eighth-note grid.", "periodPips": 416, "dimensions": 3},
  {"name": "meter_3_3_3_4", "description": "Group starts lean alternately left and right; quieter subdivisions mark the eighth-note grid.", "periodPips": 416, "dimensions": 3},
  {"name": "swing_push_3_5", "description": "Eight-beat push score with offbeats at 3/5 of each beat; peaks follow the score.", "periodPips": 512, "dimensions": 3},
  {"name": "swing_answer_3_5", "description": "Eight-beat answer score with offbeats at 3/5 of each beat; peaks follow the score.", "periodPips": 512, "dimensions": 2},
  {"name": "swing_skip_3_5", "description": "Eight-beat skip score with offbeats at 3/5 of each beat; peaks follow the score.", "periodPips": 512, "dimensions": 3},
  {"name": "swing_shuffle_3_5", "description": "Eight-beat shuffle score with offbeats at 3/5 of each beat; peaks follow the score.", "periodPips": 512, "dimensions": 3},
  {"name": "swing_push_2_3", "description": "Eight-beat push score with offbeats at 2/3 of each beat; peaks follow the score.", "periodPips": 512, "dimensions": 3},
  {"name": "swing_answer_2_3", "description": "Eight-beat answer score with offbeats at 2/3 of each beat; peaks follow the score.", "periodPips": 512, "dimensions": 2},
  {"name": "swing_skip_2_3", "description": "Eight-beat skip score with offbeats at 2/3 of each beat; peaks follow the score.", "periodPips": 512, "dimensions": 3},
  {"name": "swing_shuffle_2_3", "description": "Eight-beat shuffle score with offbeats at 2/3 of each beat; peaks follow the score.", "periodPips": 512, "dimensions": 3},
  {"name": "swing_push_5_7", "description": "Eight-beat push score with offbeats at 5/7 of each beat; peaks follow the score.", "periodPips": 512, "dimensions": 3},
  {"name": "swing_answer_5_7", "description": "Eight-beat answer score with offbeats at 5/7 of each beat; peaks follow the score.", "periodPips": 512, "dimensions": 2},
  {"name": "swing_skip_5_7", "description": "Eight-beat skip score with offbeats at 5/7 of each beat; peaks follow the score.", "periodPips": 512, "dimensions": 3},
  {"name": "swing_shuffle_5_7", "description": "Eight-beat shuffle score with offbeats at 5/7 of each beat; peaks follow the score.", "periodPips": 512, "dimensions": 3},
  {"name": "swing_push_3_4", "description": "Eight-beat push score with offbeats at 3/4 of each beat; peaks follow the score.", "periodPips": 512, "dimensions": 3},
  {"name": "swing_answer_3_4", "description": "Eight-beat answer score with offbeats at 3/4 of each beat; peaks follow the score.", "periodPips": 512, "dimensions": 2},
  {"name": "swing_skip_3_4", "description": "Eight-beat skip score with offbeats at 3/4 of each beat; peaks follow the score.", "periodPips": 512, "dimensions": 3},
  {"name": "swing_shuffle_3_4", "description": "Eight-beat shuffle score with offbeats at 3/4 of each beat; peaks follow the score.", "periodPips": 512, "dimensions": 3},
  {"name": "stick_study_01", "description": "Original R/L movement study with accented group leads, followed by its hand-swapped answer. Not an official rudiment transcription.", "periodPips": 512, "dimensions": 2},
  {"name": "stick_study_02", "description": "Original R/L movement study with accented group leads, followed by its hand-swapped answer. Not an official rudiment transcription.", "periodPips": 512, "dimensions": 2},
  {"name": "stick_study_03", "description": "Original R/L movement study with accented group leads, followed by its hand-swapped answer. Not an official rudiment transcription.", "periodPips": 512, "dimensions": 2},
  {"name": "stick_study_04", "description": "Original R/L movement study with accented group leads, followed by its hand-swapped answer. Not an official rudiment transcription.", "periodPips": 512, "dimensions": 2},
  {"name": "stick_study_05", "description": "Original R/L movement study with accented group leads, followed by its hand-swapped answer. Not an official rudiment transcription.", "periodPips": 512, "dimensions": 2},
  {"name": "stick_study_06", "description": "Original R/L movement study with accented group leads, followed by its hand-swapped answer. Not an official rudiment transcription.", "periodPips": 512, "dimensions": 2},
  {"name": "stick_study_07", "description": "Original R/L movement study with accented group leads, followed by its hand-swapped answer. Not an official rudiment transcription.", "periodPips": 512, "dimensions": 2},
  {"name": "stick_study_08", "description": "Original R/L movement study with accented group leads, followed by its hand-swapped answer. Not an official rudiment transcription.", "periodPips": 512, "dimensions": 2},
  {"name": "stick_study_09", "description": "Original R/L movement study with accented group leads, followed by its hand-swapped answer. Not an official rudiment transcription.", "periodPips": 512, "dimensions": 2},
  {"name": "stick_study_10", "description": "Original R/L movement study with accented group leads, followed by its hand-swapped answer. Not an official rudiment transcription.", "periodPips": 512, "dimensions": 2},
  {"name": "stick_study_11", "description": "Original R/L movement study with accented group leads, followed by its hand-swapped answer. Not an official rudiment transcription.", "periodPips": 512, "dimensions": 2},
  {"name": "stick_study_12", "description": "Original R/L movement study with accented group leads, followed by its hand-swapped answer. Not an official rudiment transcription.", "periodPips": 512, "dimensions": 2},
  {"name": "stick_study_13", "description": "Original R/L movement study with accented group leads, followed by its hand-swapped answer. Not an official rudiment transcription.", "periodPips": 512, "dimensions": 2},
  {"name": "stick_study_14", "description": "Original R/L movement study with accented group leads, followed by its hand-swapped answer. Not an official rudiment transcription.", "periodPips": 512, "dimensions": 2},
  {"name": "stick_study_15", "description": "Original R/L movement study with accented group leads, followed by its hand-swapped answer. Not an official rudiment transcription.", "periodPips": 512, "dimensions": 2},
  {"name": "stick_study_16", "description": "Original R/L movement study with accented group leads, followed by its hand-swapped answer. Not an official rudiment transcription.", "periodPips": 512, "dimensions": 2},
  {"name": "gesture_side_reach", "description": "An original single-point side reach gesture. Abstract motion, not a full-body dance or biomechanical recording.", "periodPips": 512, "dimensions": 2},
  {"name": "gesture_cross_reach", "description": "An original single-point cross and reach gesture. Abstract motion, not a full-body dance or biomechanical recording.", "periodPips": 512, "dimensions": 2},
  {"name": "gesture_low_scoop", "description": "An original single-point low scoop gesture. Abstract motion, not a full-body dance or biomechanical recording.", "periodPips": 512, "dimensions": 2},
  {"name": "gesture_high_arc", "description": "An original single-point high arc gesture. Abstract motion, not a full-body dance or biomechanical recording.", "periodPips": 512, "dimensions": 2},
  {"name": "gesture_corner_taps", "description": "An original single-point corner taps gesture. Abstract motion, not a full-body dance or biomechanical recording.", "periodPips": 512, "dimensions": 2},
  {"name": "gesture_diagonal_touch", "description": "An original single-point diagonal touch gesture. Abstract motion, not a full-body dance or biomechanical recording.", "periodPips": 512, "dimensions": 2},
  {"name": "gesture_box_return", "description": "An original single-point box and centre gesture. Abstract motion, not a full-body dance or biomechanical recording.", "periodPips": 512, "dimensions": 2},
  {"name": "gesture_zigzag_lift", "description": "An original single-point zigzag lift gesture. Abstract motion, not a full-body dance or biomechanical recording.", "periodPips": 512, "dimensions": 2},
  {"name": "gesture_duck_sway", "description": "An original single-point duck and sway gesture. Abstract motion, not a full-body dance or biomechanical recording.", "periodPips": 512, "dimensions": 2},
  {"name": "gesture_push_pull", "description": "An original single-point push and pull gesture. Abstract motion, not a full-body dance or biomechanical recording.", "periodPips": 512, "dimensions": 3},
  {"name": "gesture_reach_depth", "description": "An original single-point reach through depth gesture. Abstract motion, not a full-body dance or biomechanical recording.", "periodPips": 512, "dimensions": 3},
  {"name": "gesture_bow_turn", "description": "An original single-point bow and turn gesture. Abstract motion, not a full-body dance or biomechanical recording.", "periodPips": 512, "dimensions": 3},
  {"name": "gesture_heel_toe", "description": "An original single-point heel-toe abstract gesture. Abstract motion, not a full-body dance or biomechanical recording.", "periodPips": 512, "dimensions": 2},
  {"name": "gesture_hop_answer", "description": "An original single-point hop and answer gesture. Abstract motion, not a full-body dance or biomechanical recording.", "periodPips": 512, "dimensions": 2},
  {"name": "gesture_spiral_reach", "description": "An original single-point spiral reach gesture. Abstract motion, not a full-body dance or biomechanical recording.", "periodPips": 512, "dimensions": 3},
  {"name": "gesture_diamond_depth", "description": "An original single-point depth diamond gesture. Abstract motion, not a full-body dance or biomechanical recording.", "periodPips": 512, "dimensions": 3},
] as const;
export type ApprovedDefaultName = typeof approvedDefaults[number]["name"];
