#!/usr/bin/env python3
"""Register hash-locked default packs without resampling or modifying their data."""
from __future__ import annotations

import argparse
from hashlib import sha256
import json
from pathlib import Path, PurePosixPath
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'python'))
from dancerudiments_authoring import load_pack
from dancerudiments_authoring._validation import BUILTIN_NAMES
from dancerudiments_authoring.io import _cpp_string as cpp_string


def selected_patterns(lock):
    """Validate every source and selection before writing any registration files."""
    if lock.get('format') != 'dancerudiments.default-selection' or lock.get('schema_version') != 2:
        raise ValueError('Unknown default selection format')
    collections = lock.get('collections')
    if not isinstance(collections, list) or not collections:
        raise ValueError('Default selection needs at least one collection')
    seen, identifiers, headers = set(BUILTIN_NAMES), set(), set()
    result = []
    for source in collections:
        if not isinstance(source, dict):
            raise ValueError('Invalid default source')
        identifier = source.get('id')
        if not isinstance(identifier, str) or identifier in identifiers:
            raise ValueError('Invalid or duplicate collection identifier')
        identifiers.add(identifier)
        pack_file, header, namespace = source.get('pack'), source.get('header'), source.get('namespace')
        for path in (pack_file, header):
            if not isinstance(path, str) or not re.fullmatch(r'[a-zA-Z0-9_./-]+', path):
                raise ValueError('Unsafe collection path')
            parsed = PurePosixPath(path)
            if parsed.is_absolute() or '..' in parsed.parts:
                raise ValueError('Unsafe collection path')
        if header in headers:
            raise ValueError('Duplicate collection header')
        headers.add(header)
        if not isinstance(namespace, str) or not re.fullmatch(r'dancerudiments_[a-z][a-z0-9_]*', namespace):
            raise ValueError('Invalid collection namespace')
        if not (ROOT/'include'/header).is_file():
            raise ValueError('Collection header missing: '+header)
        pack = load_pack(ROOT/pack_file)
        canonical = json.dumps(pack.to_dict(), sort_keys=True, separators=(',', ':'), ensure_ascii=True, allow_nan=False)
        if sha256(canonical.encode()).hexdigest() != source.get('pack_sha256'):
            raise ValueError('Locked pack has changed: '+identifier)
        names = source.get('patterns')
        by_name = {p.name: p for p in pack.patterns}
        if not isinstance(names, list) or not names:
            raise ValueError('Default selection needs one or more names')
        for name in names:
            if not isinstance(name, str) or name not in by_name or name in seen:
                raise ValueError('Invalid, duplicate or built-in default name: '+str(name))
            seen.add(name)
            result.append((by_name[name], header, namespace))
    return result


def build(check=False):
    lock = json.loads((ROOT/'collections/defaults.json').read_text(encoding='utf-8'))
    patterns = selected_patterns(lock)
    includes = ['// Generated by tools/build_default_catalogue.py. Do not edit.']
    for header in dict.fromkeys(h for _, h, _ in patterns):
        includes.append('#include '+cpp_string(header))
    cpp = ['// Generated by tools/build_default_catalogue.py. Do not edit.',
           '// Per-pattern provenance and licences are retained in the collection headers.',
           'struct DefaultPatternEntry { RudimentInfo info; Offset3 (*sampler)(int); };',
           f'constexpr std::array<DefaultPatternEntry, {len(patterns)}> default_sampled_patterns{{{{']
    ts = ['// Generated from hash-locked default packs. All movement sampling remains C++.',
          'export const approvedDefaults = [']
    for p, _, namespace in patterns:
        dim = 3 if any(v[2] for v in p.samples) else 2 if any(v[1] for v in p.samples) else 1
        cpp.append('  {{'+f'{cpp_string(p.name)}, {cpp_string(p.description)}, {p.period_pips}, Dimension::{["one", "two", "three"][dim-1]}'+'}, &'+namespace+'::sample_'+p.name+'},')
        ts.append('  '+json.dumps(dict(name=p.name, description=p.description, periodPips=p.period_pips, dimensions=dim), ensure_ascii=True)+',')
    cpp += ['}};', '', '// Binary-search indices; catalogue order is intentionally unchanged.',
            f'constexpr std::array<std::size_t, {len(patterns)}> default_lookup_indices{{{{']
    indices = sorted(range(len(patterns)), key=lambda i: patterns[i][0].name)
    for start in range(0, len(indices), 16):
        cpp.append('  ' + ', '.join(map(str, indices[start:start+16])) + ',')
    cpp += ['}};', '']
    ts += ['] as const;', 'export type ApprovedDefaultName = typeof approvedDefaults[number]["name"];', '']
    includes += ['']
    outputs = {'include/dancerudiments/detail/default_registry.inc': '\n'.join(cpp),
               'include/dancerudiments/detail/default_includes.inc': '\n'.join(includes),
               'bindings/typescript/defaults.ts': '\n'.join(ts)}
    for name, text in outputs.items():
        dest = ROOT/name
        if check:
            if not dest.is_file() or dest.read_text(encoding='utf-8') != text:
                raise ValueError('Missing/stale default registration: '+name)
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            with dest.open('w', encoding='utf-8', newline='\n') as stream:
                stream.write(text)
    print(('Checked' if check else 'Registered')+f' {len(patterns)} sampled defaults + {len(BUILTIN_NAMES)} core movements; no resampling')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        build(args.check)
    except (ValueError, OSError, KeyError, TypeError) as exc:
        parser.exit(1, str(exc)+'\n')
